-- Seed data (generated from frontend/data). See DEPLOYMENT.md.
SET NAMES utf8mb4;
SET foreign_key_checks = 0;

INSERT INTO categories (slug,name,description,icon,image,sort_order) VALUES
('heart','Heart Care','Cardiac wellness and healthy circulation support.','HeartPulse','assets/images/product_images/Heart/Heart_omega-3.jpeg',0),
('kneePain','Knee & Joint Pain','Relief and strength for joints, knees and mobility.','Bone','assets/images/product_images/Kneepain/Kneepain_KneepainYog.jpeg',1),
('blood','Blood Care','Purifiers and tonics for healthy, clean blood.','Droplets','assets/images/product_images/Blood/BloodCare_HemossomSyrup.jpeg',2),
('conspitation','Constipation Care','Gentle relief and everyday digestive regularity.','Leaf','assets/images/product_images/Conspitation/Conspitation_AerandBhrustHardeTablets.jpeg',3),
('health','General Health','Everyday wellness, immunity and vitality boosters.','ShieldPlus','assets/images/product_images/Health/Health_J9GCapsule.jpeg',4),
('kidney','Kidney Care','Support for kidney function and urinary health.','Droplet','assets/images/product_images/Kidney/Kidney_PunnarvaChuran.jpeg',5),
('liverDisorder','Liver Care','Formulations for liver health and natural detox.','Activity','assets/images/product_images/LiverDisorder/LiverDisorder_GastoLiv100.jpeg',6),
('memory','Memory & Brain','Support focus, memory and mental clarity.','Brain','assets/images/product_images/Memory/Memory_YaadGranules.jpeg',7),
('pcodPcos','PCOD / PCOS','Hormonal balance and women''s wellness.','Flower2','assets/images/product_images/PcodPcos/PcodPcos_AshokaCordial.jpeg',8),
('piles','Piles Care','Soothing relief and comfort for piles.','Pill','assets/images/product_images/Piles/Piles_Pylofyn.jpeg',9),
('sexual','Sexual Wellness','Vitality, stamina and intimate wellness.','HeartHandshake','assets/images/product_images/Sexual/Sexaul_MakardhwajVati.jpeg',10),
('thyroid','Thyroid Care','Support for healthy thyroid function.','Stethoscope','assets/images/product_images/Thyroid/Thyroid_ThryroKyoorCapsule.jpeg',11),
('urine','Urinary Care','Prostate and urinary tract support.','Waves','assets/images/product_images/Urine/Urine_Bahumutranatak.jpeg',12);

INSERT INTO products (product_id,slug,name,category,price,discount,scheme,description,featured) VALUES
('HRT001','omega-3','Omega-3','heart',NULL,NULL,NULL,NULL,0),
('HRT002','heart-block','Heart Block','heart',350,NULL,NULL,NULL,0),
('HEA003','abc-projd','abc projd','heart',250,NULL,NULL,NULL,0),
('KNP001','kneepain-yog','Kneepain Yog','kneePain',350,NULL,NULL,NULL,0),
('KNP002','sudhasaptak-tablet','Sudhasaptak Tablet','kneePain',166,NULL,NULL,NULL,0),
('KNP003','trayodasang','Trayodasang','kneePain',180,NULL,NULL,NULL,0),
('KNP004','rhemaratna','Rhemaratna','kneePain',690,NULL,NULL,NULL,0),
('KNP005','flaxseed','Flaxseed','kneePain',395,NULL,NULL,NULL,0),
('BLD001','hemossom-syrup','Hemossom Syrup','blood',NULL,NULL,NULL,NULL,0),
('CNS001','aerand-bhrust-harde-tablets','Aerand Bhrust Harde Tablets','conspitation',130,NULL,NULL,NULL,0),
('CNS002','detozayu','Detozayu','conspitation',NULL,NULL,NULL,NULL,0),
('HLT001','j9g-capsule','J9G Capsule','health',NULL,NULL,NULL,NULL,0),
('HLT002','moringa','Moringa','health',NULL,NULL,NULL,NULL,0),
('KDN001','punnarva-churan','Punnarva Churan','kidney',NULL,NULL,NULL,NULL,0),
('LVR001','gastoliv-100','GastoLiv 100','liverDisorder',NULL,NULL,NULL,NULL,0),
('LVR002','livbond-sf','Livbond SF','liverDisorder',NULL,NULL,NULL,NULL,0),
('LVR003','livozid','Livozid','liverDisorder',NULL,NULL,NULL,NULL,0),
('LVR004','amalaki-rasyan','Amalaki Rasyan','liverDisorder',NULL,NULL,NULL,NULL,0),
('LVR005','ampachan-vati','Ampachan Vati','liverDisorder',NULL,NULL,NULL,NULL,0),
('LVR006','arogyavardhini','Arogyavardhini','liverDisorder',NULL,NULL,NULL,NULL,0),
('LVR007','livbond-drops','Livbond Drops','liverDisorder',NULL,NULL,NULL,NULL,0),
('LVR008','castor-oil','Castor Oil','liverDisorder',NULL,NULL,NULL,NULL,0),
('MEM001','yaad-granules','Yaad Granules','memory',NULL,NULL,NULL,NULL,0),
('PCD001','ashoka-cordial','Ashoka Cordial','pcodPcos',NULL,NULL,NULL,NULL,0),
('PLS001','pylofyn','Pylofyn','piles',NULL,NULL,NULL,NULL,0),
('SXL001','makardhwaj-vati','Makardhwaj Vati','sexual',NULL,NULL,NULL,NULL,0),
('SXL002','musli-pak','Musli Pak','sexual',NULL,NULL,NULL,NULL,0),
('SXL003','safed-musli-churna','Safed Musli Churna','sexual',NULL,NULL,NULL,NULL,0),
('SXL004','vanari-gutika','Vanari Gutika','sexual',NULL,NULL,NULL,NULL,0),
('SXL005','shilajit','Shilajit','sexual',NULL,NULL,NULL,NULL,0),
('THY001','thyrokyoor-capsule','ThyroKyoor Capsule','thyroid',NULL,NULL,NULL,NULL,0),
('URN001','bahumutranatak','Bahumutranatak','urine',NULL,NULL,NULL,NULL,0),
('URN002','proston-tablet','Proston Tablet','urine',NULL,NULL,NULL,NULL,0);

INSERT INTO product_images (product_id,path,sort_order) VALUES
('HRT001','assets/images/product_images/Heart/Heart_omega-3.jpeg',0),
('HRT002','assets/images/product_images/Heart/Heartcare_HeartBlock.jpeg',0),
('HEA003','assets/images/product_images/heart/whatsapp-image-2026-09-02-at-13-24-44-13088e5b.jpeg',0),
('HEA003','assets/images/product_images/heart/whatsapp-image-2026-09-02-at-13-24-44-b69605fc.jpeg',1),
('KNP001','assets/images/product_images/Kneepain/Kneepain_KneepainYog.jpeg',0),
('KNP002','assets/images/product_images/Kneepain/Kneepain_SudhasaptakTablet.jpeg',0),
('KNP003','assets/images/product_images/Kneepain/Kneepain_Trayodasang.jpeg',0),
('KNP004','assets/images/product_images/Kneepain/kneePain_Rhemaratna.jpeg',0),
('KNP005','assets/images/product_images/Kneepain/kneepain_Flaxseed.jpeg',0),
('BLD001','assets/images/product_images/Blood/BloodCare_HemossomSyrup.jpeg',0),
('CNS001','assets/images/product_images/Conspitation/Conspitation_AerandBhrustHardeTablets.jpeg',0),
('CNS002','assets/images/product_images/Conspitation/constipation_Detozayu.jpeg',0),
('HLT001','assets/images/product_images/Health/Health_J9GCapsule.jpeg',0),
('HLT002','assets/images/product_images/Health/Health_moringa.jpeg',0),
('KDN001','assets/images/product_images/Kidney/Kidney_PunnarvaChuran.jpeg',0),
('LVR001','assets/images/product_images/LiverDisorder/LiverDisorder_GastoLiv100.jpeg',0),
('LVR002','assets/images/product_images/LiverDisorder/LiverDisorder_LivbondSF.jpeg',0),
('LVR003','assets/images/product_images/LiverDisorder/LiverDisorder_Livozid.jpeg',0),
('LVR004','assets/images/product_images/LiverDisorder/Liverdisorder_amalakiRasyan.jpeg',0),
('LVR004','assets/images/product_images/aamalikaRasayan.jpeg',1),
('LVR004','assets/images/product_images/amalakiRashyan.jpeg',2),
('LVR005','assets/images/product_images/LiverDisorder/Liverdisorder_ampachanVati.jpeg',0),
('LVR006','assets/images/product_images/LiverDisorder/Liverdisorder_arogyavardhnin.jpeg',0),
('LVR007','assets/images/product_images/LiverDisorder/Liverrdisorder_LivbondDrops.jpeg',0),
('LVR008','assets/images/product_images/LiverDisorder/lLiverdisorder_castorOil.jpeg',0),
('MEM001','assets/images/product_images/Memory/Memory_YaadGranules.jpeg',0),
('PCD001','assets/images/product_images/PcodPcos/PcodPcos_AshokaCordial.jpeg',0),
('PLS001','assets/images/product_images/Piles/Piles_Pylofyn.jpeg',0),
('SXL001','assets/images/product_images/Sexual/Sexaul_MakardhwajVati.jpeg',0),
('SXL002','assets/images/product_images/Sexual/Sexual_MusliPak.jpeg',0),
('SXL003','assets/images/product_images/Sexual/Sexual_SafedMusliChurna.jpeg',0),
('SXL004','assets/images/product_images/Sexual/Sexual_vanarigutika.jpeg',0),
('SXL005','assets/images/product_images/Sexual/sexualwellnes_shilajit.jpeg',0),
('THY001','assets/images/product_images/Thyroid/Thyroid_ThryroKyoorCapsule.jpeg',0),
('URN001','assets/images/product_images/Urine/Urine_Bahumutranatak.jpeg',0),
('URN002','assets/images/product_images/Urine/Urine_ProstonTablet.jpeg',0);

INSERT INTO product_sizes (product_id,size_label,sort_order) VALUES
('HRT002','30 Capsule',0),
('HEA003','30 capsule',0),
('KNP001','30 Capsule',0),
('KNP002','30 Tablets',0),
('KNP004','30 Capsule',0),
('KNP005','60 Capsule',0),
('CNS001','60 Tablets',0);

INSERT INTO admin_users (username,password_hash) VALUES ('admin','$2y$12$TGPo2tinG.LZqAVY51Mzbe1VbowuAMsa35SXesOpFPjsIEtpqYTS6');

SET foreign_key_checks = 1;
